#!/bin/sh

echo 57 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio57/direction
echo 0 > /sys/class/gpio/gpio57/active_low

echo 58 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio58/direction
echo 0 > /sys/class/gpio/gpio58/active_low

